name: Code Formatter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      ##  If you want to check the formatting without making changes, uncomment the following line
      #- name: Run Prettier
      #  run: npx prettier --check .

      - name: Run Prettier and fix
        run: npx prettier --write . '!.github/workflows/**'

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}

          # Pull first to avoid non-fast-forward errors
          git pull origin main --rebase

          git add .
          git commit -m "chore: auto-format code" || echo "No changes to commit"
          git push

      - name: Set Environment Variables
        run: echo "NEXT_PUBLIC_WEATHER_API_KEY=${{ secrets.WEATHER_APIKEY }}" >> $GITHUB_ENV

      - name: Build App
        run: npm run build

      - name: Deploy
        run: npm run deploy
