name: Code Formatter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run Prettier and fix
        run: npx prettier --write .

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: auto-format code" || echo "No changes to commit"
          git push
